### ISSUE TITLE
Not working? 

### ISSUE THREAD

**Issue by LightRO** [nebulabroadcast/nebula-cloud#1]
Hello together,

I wanted to ask once if the system still works at all? Because if I follow the instructions and edit the parameters in the hostinstall.sh in relation to the nginx, I get at least when calling the default page the message 502 Bad Gateway. If I now create the config correctly and then build a subdomain from it, then the subdomain also gets a 502 bad gateway again. I also do not notice that the vagrant / virtualbox was configured or started.

Many greetings,
LightRO

**Comment by martastain** [comment]
It does work - we still use it in production, but it should be considered a legacy project (I'll archive it soon) since we're switching to Docker in new installations. The only use-case for this is when you need to deploy multiple nebula instances (to handle more completely different clients) on the same machine.

And yes - vagrant machines have to be started manually. As for configuration, for each Nebula instance you create a directory in the "sites" dir, its name will be the "site_name" (for example a station name). In this directory you will have two subdirectories:
`machines` and `template`. Contents of the `template` directory is the same you would use in nebula-setup (__init__.pyt, actions, services) and within the `machines` subdir, you create a file for each virtual machine you will run. The name of the file will become its hostname. The contents looks like follows:

```
ip="192.168.32.65"
cpus=4
memory=8192
roles=(
    "nebula"
    "hub"
    "ffmpeg"
)
```

Only one of the machines should have role "hub".
Then you run `./reconfigure.sh SITENAME`, go to /var/nebula-cloud/SITENAME/ and run `vagrant up` in each of the subdirectories.

But as I said - there's not much you can gain using this repository. https://github.com/immstudios/nebula-demo is the future.
